### ISSUE TITLE
Plugins created in the editor not being saved (Chrome)

### ISSUE THREAD

**Issue by Farmer-Eds-Shed** [symbioquine/farmOS_asset_link#2] opened 2022-08-31 14:19 UTC
Plugins created in the editor not being saved to IndexedDB in browser cache in Chrome.
Works as expected on Firefox.

**Comment by symbioquine** [comment] 2022-08-31 16:31
I can reproduce this. In Chrome I get an error trying to save a plugin from the editor;

```
runtime-core.esm-bundler.js:226 Error: Unsupported local plugin URL: indexeddb://asset-link/data/AddNewBalesToInventory.alink.vue
    at sd._validateUrl (AssetLinkLocalPluginStorageCore.js:52:13)
    at sd.writeLocalPlugin (AssetLinkLocalPluginStorageCore.js:37:10)
    at Proxy.createNewLocalPlugin (eval at A (vue3-sfc-loader.esm.js:81:9271), <anonymous>:3:3203)
```

![image](https://user-images.githubusercontent.com/30754460/187730229-08aac0ea-fede-4397-9e78-5f24d4f403a5.png)

It looks like Chrome is parsing the `indexeddb://` url differently than Firefox does.

In Firefox `new URL("indexeddb://asset-link/data/AddNewBalesToInventory.alink.vue")` produces;

![image](https://user-images.githubusercontent.com/30754460/187730864-355d225c-d93c-4001-960c-32529dd4cb56.png)

**Comment by symbioquine** [comment] 2022-08-31 17:30
This seems to be a long-standing issue with Chrome compared with Safari/Edge/Firefox(recent versions)/Node/etc;

* https://bugs.chromium.org/p/chromium/issues/detail?id=869291
* https://felixfbecker.github.io/whatwg-url-custom-host-repro/

**Comment by symbioquine** [comment] 2022-08-31 19:53
Fixed by https://github.com/symbioquine/farmOS_asset_link/commit/ddee9590b3ed005d4f81c27fe1d38d58a22c294b in the [0.6.1 release](https://www.drupal.org/project/farmos_asset_link/releases/0.6.1)

**Closed as completed by symbioquine** 2022-08-31 19:53 UTC
Labels: bug
